import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalErrorBoundary } from '@root/components/GlobalErrorBoundary';
import {  ConfigProvider } from 'antd';
import zhCN from 'antd/es/locale/zh_CN';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="zh">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ConfigProvider locale={zhCN}>
            <GlobalErrorBoundary>
              {children}
            </GlobalErrorBoundary>
          </ConfigProvider>
      </body>
    </html>
  );
}

